---
sudo: required
language: python
python: 
  - "3.8"

services:
  - docker

addons:
  apt:
    packages:
    - python3-pip

install:
  - python3 -m pip install "molecule[docker, lint, ansible]"

  # Check molecule version
  - molecule --version

  # Check ansible version
  - ansible --version

  # Check installed docker driver
  - pip freeze | grep docker

  # Check installed linting
  - pip freeze | grep lint
  - pip freeze | grep flake8

script:
  - molecule --version